/* eslint-disable react/prop-types */
/* eslint-disable react/jsx-key */
import { createContext, useReducer } from "react";
import project1 from "../assets/project1.png";
import project2 from "../assets/project2.jpg";

import { FaJava, FaReact, FaGithub, FaPython } from "react-icons/fa";
import { SiMysql } from "react-icons/si";
import { SiOpencv } from "react-icons/si";
import { GiArtificialIntelligence } from "react-icons/gi";

const DEFAULT_CONTEXT = {
  projectList: [],
};

export const MyProject = createContext(DEFAULT_CONTEXT);

const myProjectReducer = (currMyProject, action) => {
  return currMyProject;
};

const MyProjectProvider = ({ children }) => {
  const [projectList, dispachMyProjects] = useReducer(
    myProjectReducer,
    DEFAULT_PROJECT_LIST
  );

  return (
    <MyProject.Provider value={{ projectList }}>{children}</MyProject.Provider>
  );
};

const projectDescriptions = {
  instituteDataManagement:
    "It is a solution tool designed to track, maintain, manage, and store all the data generated by the Institute. We created this project to overcome existing problems faced by the CDAC Bangalore Institute. The task includes Planning, writing, designing, building, and testing this system as per requirements. Platforms used for this project are Spring Boot (Backend), MySQL Database, Rest Web Services, and ReactJs (Frontend). We developed this project using Agile Methodologies.",
  faceMaskDetection:
    "In this project, we developed a machine learning module Realtime Face Mask Detector with Python to detect whether the person on the webcam is wearing a mask or not. Platforms used for this project are Python, OpenCV, and Machine Learning.",
};

const DEFAULT_PROJECT_LIST = [
  {
    id: "1",
    title: "Portfolio",
    body: projectDescriptions.instituteDataManagement,
    skills: [<FaJava />, <SiMysql />, <FaReact />, <FaGithub />],
    link: "https://tejasbhosale17.github.io/tejasportfolio.github.io/",
    imglink: project1,
  },
  {
    id: "2",
    title: "Face Mask Detection and Monitoring System",
    body: projectDescriptions.faceMaskDetection,
    skills: [<FaPython />, <SiOpencv />, <GiArtificialIntelligence />],
    link: "https://www.linkedin.com/in/tejas-bhosale-195871159/",
    imglink: project2,
  },
];

export default MyProjectProvider;
