import { FaGithub, FaJava, FaReact } from "react-icons/fa";
import { SiMysql } from "react-icons/si";
import smsImgLink from "../assets/project1.png";
/* eslint-disable react/prop-types */
const Project = ({ project }) => {
  const projectDescriptions = {
    instituteDataManagement:
      "It is a solution tool designed to track, maintain, manage, and store all the data generated by the Institute. We created this project to overcome existing problems faced by the CDAC Bangalore Institute. The task includes Planning, writing, designing, building, and testing this system as per requirements. Platforms used for this project are Spring Boot (Backend), MySQL Database, Rest Web Services, and ReactJs (Frontend). We developed this project using Agile Methodologies.",
    faceMaskDetection:
      "In this project, we developed a machine learning module Realtime Face Mask Detector with Python to detect whether the person on the webcam is wearing a mask or not. Platforms used for this project are Python, OpenCV, and Machine Learning.",
  };
  return (
    /* <div className="col">
      { <div className="card project">
        <img
          src={project.imglink}
          className="project-image"
          alt="PROJECT Image"
        />
        <div className="card-body">
          <h5 className="card-title">{project.title}</h5>
          <p className="card-text">{project.body}</p>
          <p className="card-text">{project.skills}</p>
          <a href={project.link} className="btn btn-primary">
            GitHub
          </a>
        </div>
      </div> }*/
    /*{ <center className="project-content-center">
        <div className="card mb-3 project" style={{ maxWidth: "540px" }}>
          <div className="row g-0">
            <div className="col-md-8">
              <div className="card-body">
                <h5 className="card-title">{project.title}</h5>
                <p className="card-text" style={{ textAlign: "justify" }}>
                  {project.body}
                </p>
                <p className="card-text">{project.skills}</p>
                <a href={project.link} className="btn btn-primary">
                  GitHub
                </a>
              </div>
            </div>
            <div className="col-md-4">
              <img
                src={project.imglink}
                className="project-image"
                alt="PROJECT Image"
              />
            </div>
          </div>
        </div>
      </center> }*/

    // <div className="col">
    //   <div className="card shadow-sm">
    //     <img
    //       src={project.imglink}
    //       className="project-image"
    //       alt="PROJECT Image"
    //     />
    //     <title>{project.title}</title>
    //     <div className="card-body">
    //       <p className="card-text">{project.body}</p>
    //       <p className="card-text">{project.skills}</p>
    //       <a href={project.link} className="btn btn-primary">
    //         GitHub
    //       </a>
    //     </div>
    //   </div>
    // </div>

    <div className="container">
      <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div className="col">
          <div className="card shadow-sm">
            <img
              src={smsImgLink}
              className="project-image"
              alt="PROJECT Image"
            />
            <title>Student Management System</title>
            <div className="card-body">
              <p className="card-text">
                {projectDescriptions.instituteDataManagement}
              </p>
              <p className="card-text">
                {" "}
                [
                <FaJava
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <SiMysql
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaReact
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaGithub
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                , ]
              </p>
              <a
                href="https://tejasbhosale17.github.io/tejasportfolio.github.io/"
                className="btn btn-primary"
              >
                GitHub
              </a>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card shadow-sm">
            <img
              src={smsImgLink}
              className="project-image"
              alt="PROJECT Image"
            />
            <title>Student Management System</title>
            <div className="card-body">
              <p className="card-text">
                {projectDescriptions.instituteDataManagement}
              </p>
              <p className="card-text">
                {" "}
                [
                <FaJava
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <SiMysql
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaReact
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaGithub
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                , ]
              </p>
              <a
                href="https://tejasbhosale17.github.io/tejasportfolio.github.io/"
                className="btn btn-primary"
              >
                GitHub
              </a>
            </div>
          </div>
        </div>
        <div className="col">
          <div className="card shadow-sm">
            <img
              src={smsImgLink}
              className="project-image"
              alt="PROJECT Image"
            />
            <title>Student Management System</title>
            <div className="card-body">
              <p className="card-text">
                {projectDescriptions.instituteDataManagement}
              </p>
              <p className="card-text">
                {" "}
                [
                <FaJava
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <SiMysql
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaReact
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                ,
                <FaGithub
                  style={{ height: "50px", width: "50px", paddingRight: "5px" }}
                />
                , ]
              </p>
              <a
                href="https://tejasbhosale17.github.io/tejasportfolio.github.io/"
                className="btn btn-primary"
              >
                GitHub
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
export default Project;
